services:

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  proxy:
    container_name: proxy
    build:
      dockerfile: proxy-service/docker/proxy/Dockerfile
      context: .
    ports:
      - "9050:9050"
      - "9051:9051"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - micro-pulse-finder:/data/db

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - ./remote/terraform:/workspace
      - ~/.ssh/vult:/root/.ssh:ro
    working_dir: /workspace
    entrypoint: ["/bin/sh", "-c", "apk update && apk add --no-cache rsync && tail -f /dev/null"]
    environment:
      - TF_LOG=TRACE

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./shared/observability/docker/prometheus/config.yml:/etc/prometheus/config.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/config.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  micro-pulse-finder: