server:
  # Port where Promtail's web interface and API will be available
  http_listen_port: 9080
  grpc_listen_port: 0  # Disable gRPC since we're not using it

positions:
  # Track the last read position in log files (so Promtail doesn't re-read old logs)
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  # Send logs to Loki

scrape_configs:
  - job_name: "nats-service-logs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "nats-service-logs"
          service: "nats-service"
          __path__: /var/log/nats-service/*.log

  - job_name: "url-service-logs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "url-service-logs"
          service: "url-service"
          __path__: /var/log/url-service/*.log

  - job_name: "proxy-service-logs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "proxy-service-logs"
          service: "proxy-service"
          __path__: /var/log/proxy-service/*.log
